version: "3.8"
services:

  db-test:
    image: postgres:12
    volumes:
      - app-db-test-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=nersdb_test
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata

  api:
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    environment:
      - POSTGRES_SERVER=db-test
      - POSTGRES_DB=nersdb_test
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=1234
      - SQLALCHEMY_DATABASE_URI=postgresql://app:1234@db-test/nersdb_test
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    depends_on:
      - db-test
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-'true'}
    command: sh -c "sleep 30 && pytest"


volumes:
  app-db-test-data:
